### ISSUE TITLE
Embedded resource relations

### ISSUE THREAD

**Issue by cbandy** [nvellon/hal#1]
Resources are [embedded as a JSON object](https://tools.ietf.org/html/draft-kelly-json-hal-06#section-4.1.2), but they seem to be implemented as an slice.

**Comment by nvellon** [comment]
What do you suggest?

**Comment by nvellon** [comment]
I'm afraid I don't get your point... 

Using slices as the base structures was the most flexible way I've found to serialize into JSON. The main idea was keeping the structs declaration separated from HAL-related code, so the getMap interface implementation seemed convenient...

But, in any case, if you could make your point more clear, I'll be happy to help.

**Comment by cbandy** [comment]
How does one define the relationship (link relation) of the embedded resources to the current resource?

**Comment by nvellon** [comment]
For example, you set the self relation whenever you create a resource:

```
r := hal.NewResource(somo_struct, "/resource/1")
```

Then, if you need to add another relation to the resource, you simply do:

```
r.AddNewLink("other_relation", "/related/stuff")
```

You'd have to set all relations before embedding... At the moment there is no way of adding relations to an already embedded resource.

**Comment by cbandy** [comment]
https://tools.ietf.org/html/draft-kelly-json-hal-06#section-4.1.2

**Comment by nvellon** [comment]
Sorry mate, I was reading all the wrong way...

I could add an extra param to the Embed method, and an extra method for embedding slices of resources:

```
r.Embed("relation", er)

// er_slice := make([]*Resource)
r.EmbedCollection("relation", er_slice)
```

Sounds good?

**Comment by cbandy** [comment]
Maybe something like [http.Header](http://golang.org/pkg/net/http/#Header).

**Comment by nvellon** [comment]
I'm lost with that one... could you write an example of how would that work?

I was suggesting this:

https://github.com/nvellon/hal/blob/relations/hal.go#L75

https://github.com/nvellon/hal/blob/relations/examples/embedded.go#L51-L56

**Comment by nvellon** [comment]
Take a look at this:

https://github.com/nvellon/hal/blob/relations/hal.go#L44-L70

**Comment by cbandy** [comment]
Nice. The convenience of `http.Header.Get()` is to mirror `.Set()`, so one can treat it as single value:

```go
func (e Embedded) Get(rel Relation) *Resource {}
```

I wonder if we should render a 1-element slice without the array during `MarshalJSON()`? I'm okay with either way.

**Comment by chadkouse** [comment]
@cbandy I think if you embed a 1 element slice it should remain an array when rendered.  If the user doesn't want that they should embed a single resource.

**Comment by chadkouse** [comment]
@nvellon :+1: on the relations branch  - although the type block was a little disorienting at first

**Comment by chadkouse** [comment]
I'm realizing it makes things pretty complicated to try to determine when things should be a single element array vs a single object (not in an array).  So maybe as @cbandy said we should just be ok with it being a single element array always... Thoughts?

**Comment by chadkouse** [comment]
I took a crack at handling multiple scenarios here, check out #2 and give me your feedback - thanks

**Comment by nvellon** [comment]
@cbandy @chadkouse Sorry guys, I'm quite busy at the mo... hopefully I'll get back at some point this weekend. Thanks

**Comment by nvellon** [comment]
Finally got to merge your PR @chadkouse. You've done a good job. Thank you!

Will merge all this into master as soon as I found out how Go packages versioning works.

**Comment by nvellon** [comment]
Done!
