### ISSUE TITLE
Question: Mapper instead of json fields

### ISSUE THREAD

**Issue by scisci** [nvellon/hal#5]
Just a general question after a quick glance at this project. Why was it necessary to use a Mapper interface rather than using fields, as is normally done for json marshalling?

```
User {
  id string `json:"id"`
}
```

I'm sure there is a good reason, so just interested.

**Comment by nvellon** [comment]
Mainly for a "design aproach", which is: I wanted the Hal implementation code separated from client/business structures. Some sort of separation of concerns...

You might ask: instead of forcing hal.Mapper implementation, why don't just expect an interface{} and do the magic inside? And the answer is that that could be quite messy and I didn't have the time to give it a try given that implementing hal.Mapper ends up being pretty simple and clean for both user and maintainer...

In any case, if want to give it a try, just feel free to fork and PR your suggestions ;)

**Comment by scisci** [comment]
OK thanks for addressing it. I might try it out. As you said the Mapper interface is quite easy and its working now which is good! Only two reasons I might go with the other approach is that 1) It seems like standard go practice, since HAL gets written to json, it seems follow the same practice for writing objects to json and 2) Any object that you want to write to hal can't already have a method called GetMap() Anyway, thanks for the library its got me started with HAL really fast!

**Comment by nvellon** [comment]
I've made a quick try... it uses the encoding/json reflection to convert interface{} into hal.Entry.

SHA: cc0ef43f210f875e68b2ed41e9a04ef91dff433b

**Comment by scisci** [comment]
Wow @nvellon thanks! I will try to test this out as soon as I can, I've already implemented a few endpoint using the Mapper, but will convert them over to this to try it out. another benefit of the json tags is that api documentation generators can use them to generate docs for the structures.

**Comment by nvellon** [comment]
Be aware that this option is much slower than the implementing hal.Mapper
way: it makes [a very lazy and not nice] use of the reflection mechanisms
in encodin/json just by marshaling and unmarshaling your struct into a
hal.Entry map. So there's plenty of extra code that have to be executed,
some of it unnecesary... Haven't had time to run performance tests, but let
me know if you do.

**Comment by alvarowolfx** [comment]
I tried to solve this problem on #6, following @nvellon idea, but using the reflect package directly to generate the map[string]interface{} needed by the Mapper Interface. What do you think of this solution ? By the way, congrats by the good work on this library @nvellon

**Comment by nvellon** [comment]
@alvarowolfx that looks much better! I think I'd only keep the Mapper as an option that might be useful for performance matters, but keeping you proposal as default behaviour... What do you think?

**Comment by alvarowolfx** [comment]
Can be a good solution @nvellon, first verify if the struct conforms with Mapper interface then use the  GetMap method, if not, use my solution with the reflect package. How can we do this now ? I send my code in another branch so we can continue this new implementation ?

**Comment by nvellon** [comment]
Great, just push into another branch! Thanks

Enviado desde mi iPhone

**Comment by nvellon** [comment]
@alvarowolfx I've just merged your PR. Good job. Thank you!

The lib now supports translation from any struct into hal format. It also keeps hal.Mapper interface for backward compatibility and performance matters.

I'll run a few tests myself, update the doc and create a new tag in a couple of days.
