### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by mvader** [nvellon/hal#7]
It would be great to include versioning (via gopkg.in if possible) to this library. Yesterday's merge had breaking changes and today we've noticed that our tests were broken with no notice at all. That would have not happened with versioning.

Thanks

**Comment by nvellon** [comment]
Sorry about that. I would have thought that people's proyects depends on repo tags instead of the master branch...

I'll take a look into gopkg.in. Any other suggestions will be most wellcome ;)

Enviado desde mi iPhone

**Comment by cbandy** [comment]
> That would have not happened with versioning.

That can also be avoided with vendoring.

**Comment by nvellon** [comment]
Closing this issue since vendoring is currently supported by the go runtime and there're a few tools allowing git-like dependencies... such as this one.

In any case, feel free to re-open.
