### ISSUE TITLE
Specifying template links not possible because of string-only values in _links

### ISSUE THREAD

**Issue by gustav-b** [nvellon/hal#8]
The current API doesn't allow setting the `templated` attribute to `true` for template links as described in [the HAL specification](http://stateless.co/hal_specification.html). The reason is that `hal.LinkAttr` is defined as `map[string]string`, meaning that it can't take a bool value.

Changing this define to `map[string]interface{}` would allow one to define template links as:
```go
l := hal.NewLink("/orders{?id}", hal.LinkAttr{"templated": true})
r.AddLink("ea:find", l)
```
But maybe there is a reason for forcing string values in links that I don't see.

**Comment by nvellon** [comment]
There wasn't any reason, the use case didn't come up.

If you feel like giving it a try, your PR would be welcome.

Enviado desde mi iPhone
